// Builds the avatar set from the source images in apps/web/avatars-src/.
//
//   pnpm --filter @kontext/web avatars
//
// For every avatars-src/<name>.(png|jpg|jpeg|webp|svg|gif):
//   • the file name becomes the character id (lower-case, ascii, "-" separated)
//   • the image is written to public/avatars/<id>.webp as a 320×320 square:
//       – transparent background → margins trimmed, fitted with a little
//         padding; the app draws the coloured circle behind the character
//       – opaque artwork (own background) → centre-cropped, full bleed
//   • packages/shared/src/avatar-catalog.ts is regenerated with the id list,
//     which the server uses to assign avatars and the web app uses to render.
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import sharp from 'sharp'

const here = path.dirname(fileURLToPath(import.meta.url))
const srcDir = path.resolve(here, '../avatars-src')
const outDir = path.resolve(here, '../public/avatars')
const catalogFile = path.resolve(here, '../../../packages/shared/src/avatar-catalog.ts')

const SIZE = 320 // output px (rendered at ≤128 css px → crisp on 2× screens)
const PADDING = 0.06 // fraction of SIZE kept clear on each side
const EXT = '.webp'
const INPUT_RE = /\.(png|jpe?g|webp|svg|gif)$/i

// Ukrainian (plus the few extra Russian letters) \u2192 latin, so "\u041f\u0430\u043d\u0434\u0430.png" \u2192 "panda".
const CYR = {
  а: 'a',
  б: 'b',
  в: 'v',
  г: 'h',
  ґ: 'g',
  д: 'd',
  е: 'e',
  є: 'ie',
  ж: 'zh',
  з: 'z',
  и: 'y',
  і: 'i',
  ї: 'i',
  й: 'i',
  к: 'k',
  л: 'l',
  м: 'm',
  н: 'n',
  о: 'o',
  п: 'p',
  р: 'r',
  с: 's',
  т: 't',
  у: 'u',
  ф: 'f',
  х: 'kh',
  ц: 'ts',
  ч: 'ch',
  ш: 'sh',
  щ: 'shch',
  ь: '',
  ю: 'iu',
  я: 'ia',
  ы: 'y',
  э: 'e',
  ё: 'io',
  ъ: '',
}

function slug(fileName, index) {
  const id = fileName
    .replace(INPUT_RE, '')
    .toLowerCase()
    .replace(/[\u0430-\u044f\u0451\u0454\u0456\u0457\u0491]/g, (ch) => CYR[ch] ?? '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-(\d+)$/, '_$1') // "sheep-2" would collide with the "-<colour>" suffix
  return /[a-z]/.test(id) ? id : `character-${index + 1}`
}

let files
try {
  files = (await readdir(srcDir)).filter((f) => INPUT_RE.test(f)).sort()
} catch {
  files = []
}
if (files.length === 0) {
  console.error(`No images found in ${srcDir}\nDrop png/jpg/webp/svg files there and re-run.`)
  process.exit(1)
}

await rm(outDir, { recursive: true, force: true })
await mkdir(outDir, { recursive: true })

const ids = []
for (const [index, file] of files.entries()) {
  const id = slug(file, index)
  if (ids.includes(id)) {
    console.warn(`skip ${file}: duplicate id "${id}"`)
    continue
  }
  const source = sharp(path.join(srcDir, file), { density: 300 })
  const stats = await source.clone().ensureAlpha().stats()
  // Alpha channel min < 255 → the image has transparency somewhere.
  const transparent = (stats.channels[3]?.min ?? 255) < 255
  let kind
  if (transparent) {
    // Character on a transparent background: trim the margins and fit it
    // into the square with a little padding; the app draws the colour behind.
    kind = 'transparent'
    const inner = Math.round(SIZE * (1 - PADDING * 2))
    const character = await source
      .clone()
      .ensureAlpha()
      .trim({ threshold: 8 })
      .resize(inner, inner, { fit: 'inside', withoutEnlargement: false })
      .toBuffer()
    await sharp({
      create: {
        width: SIZE,
        height: SIZE,
        channels: 4,
        background: { r: 0, g: 0, b: 0, alpha: 0 },
      },
    })
      .composite([{ input: character, gravity: 'centre' }])
      .webp({ quality: 88, alphaQuality: 90 })
      .toFile(path.join(outDir, id + EXT))
  } else {
    // Opaque artwork (own background): centre-crop to a square, full bleed.
    kind = 'full-bleed'
    await source
      .clone()
      .resize(SIZE, SIZE, { fit: 'cover', position: 'attention' })
      .webp({ quality: 88 })
      .toFile(path.join(outDir, id + EXT))
  }
  ids.push(id)
  console.log(`${file} → public/avatars/${id}${EXT} (${kind})`)
}

if (ids.length === 0) {
  console.error('Nothing written.')
  process.exit(1)
}

const catalog = `/**
 * Avatar character catalogue.
 *
 * GENERATED by \`pnpm --filter @kontext/web avatars\` from the images in
 * apps/web/avatars-src/ — do not edit by hand once images are in use.
 *
 * While \`AVATAR_IMAGE_EXT\` is null the web app draws the built-in SVG animals;
 * once the script runs it points at \`apps/web/public/avatars/<character><ext>\`.
 */
export const AVATAR_CHARACTERS = [
${ids.map((id) => `  '${id}',`).join('\n')}
] as const

export const AVATAR_IMAGE_EXT: string | null = '${EXT}'
`
await writeFile(catalogFile, catalog)
console.log(`wrote ${path.relative(process.cwd(), catalogFile)} (${ids.length} characters)`)
