/**
 * Avatar character catalogue.
 *
 * GENERATED by `pnpm --filter @kontext/web avatars` from the images in
 * apps/web/avatars-src/ — do not edit by hand once images are in use.
 *
 * While `AVATAR_IMAGE_EXT` is null the web app draws the built-in SVG animals;
 * once the script runs it points at `apps/web/public/avatars/<character><ext>`.
 */
export const AVATAR_CHARACTERS = [
  'amber-fangs',
  'coral-surprised',
  'green-goofy',
  'lime-bored',
  'lime-scream',
  'magenta-laugh',
  'navy-cyclops',
  'navy-wink',
  'orange-tongue',
  'sky-smile',
  'teal-grin',
  'teal-sad',
  'violet-happy',
] as const

export const AVATAR_IMAGE_EXT: string | null = '.webp'
